# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4274d62d36b86e568268b565625b153f3eb3a5890223ccb9f8435cebe3648a069ad25643e93c1ba9faac4d949197e149aee7a612c40f1e5cce067376d130b094

test:
  secret_key_base: b9c46585a34e29f2ed06121f89c5ca0e48c39bb77cd3246788163de0db547be0797e13bdc69fded5f81a6c92cbe343c8355f7d52b7c65475b03269174e6bfd8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
